Added workflow to use FFMPEG to convert video to gif
warpdotdev/workflows pull request #135
Opened 2023-01-30 01:35 UTC by olsoma13

## Discord username (optional) please include so we can attribute you with our Contributor role (like so elvis#4747)
molson#0565
## Description of changes (updated or new workflows)
New workflow to convert videos to gifs

2023-04-07 19:56 UTC, alokedesai requested changes
Looks great, thank you for contributing! I had a few small comments but nothing major :D

2023-04-07 19:56 UTC, alokedesai commented on specs/ffmpeg/vid_to_gif.yml
> +name: ffmpeg to convert a video to gif
How about "Convert a video to gif using ffmpeg"?

2023-04-07 19:56 UTC, alokedesai commented on specs/ffmpeg/vid_to_gif.yml
> +source_url: "https://github.com/cyburgee/ffmpeg-guide"
nit: could we link to the actual section of this guide where it talks about converting from video to gif?
https://github.com/cyburgee/ffmpeg-guide#video-to-gif

2023-08-31 08:27 UTC, elviskahoro commented
@olsoma13 just reaching back out to see if you could make a few small changes based on aloke's feedback once you have free cycles

2023-09-05 07:36 UTC, elviskahoro commented
Closing for now, please re-open if you get the bandwidth to resolve the comments.

2023-09-05 07:36 UTC, closed without merging