add nativescript workflows
warpdotdev/workflows pull request #38
Opened 2022-04-10 09:08 UTC by erodriguezh

Hi Workflow Team,

I added the workflows for NativeScript.

Best

2022-04-10 17:54 UTC, elviskahoro commented
@erodriguezh I'm gonna add aloke as a reviewer. Thanks again for opening a PR and adding native script! You've added a lot of workflows, we appreciate it a lot!

2022-04-11 04:48 UTC, elviskahoro commented
@erodriguezh if you're in our discord what's your username so I can add the contributor discord role?

2022-04-11 06:13 UTC, erodriguezh commented
@elviskahoro my username is erodr#3149, I'm not sure if the hash number is necessary 😅

2022-04-11 20:12 UTC, ianhodge requested changes
Hey @erodriguezh ! Thank you SO much for creating all these workflows. This is super beneficial to the whole Warp community. 

One small note - right now the title and descriptions of these workflows are a little vague and I think should be a little more specific to nativescript. For instance the unit test workflow "Configures your project for unit testing with a selected framework" could be "Configures your NativeScript project for unit testing with a selected framework." This way, users who are not searching specifically for a NativeScript command won't be confused by the contents of the workflow, and users who want to search for a NativeScript command can find it more easily. 

Let me know if you have any questions and thank you so much again for contributing! This is really amazing.

2022-04-12 07:08 UTC, erodriguezh commented
Hi @ianhodge,

Thanks for your feedback, it is a good point. Please check the latest commit, I added accuracy to the titles and descriptions.

2022-04-12 15:41 UTC, ianhodge approved these changes
Looks great! Thank you for addressing the feedback :)

2022-04-14 05:36 UTC, erodriguezh commented
There seemed to be an issue with double quotes, should be ok now.

2022-04-19 14:15 UTC, alokedesai commented on specs/nativescript/add_platform.yaml
> +  - tns
Hey @erodriguezh! Thanks so much for your contribution. One thing i'm noticing is that we have duplicated tags for `ns`, `tns`, and `nativescript` here. Would it be possible to consolidate and just have the `nativescript` tag instead?

2022-04-20 14:31 UTC, merged