feat[specs]: add vercel-cli and signing git commit
warpdotdev/workflows pull request #48
Opened 2022-04-14 21:25 UTC by umarhadi

Hi everyone!

I added 13 workflows for vercel-cli and 1 workflow for git

Thank you 🙌🏻

2022-04-17 07:03 UTC, elviskahoro commented
@umarhadi Are you in our discord, if so what's your username so I can add the Contributor role?

2022-04-17 16:23 UTC, umarhadi commented
> @umarhadi Are you in our discord, if so what's your username so I can add the Contributor role?

Yes, I’m in Discord. umar#8211 is my username, Thank you! ✨

2022-04-18 19:34 UTC, elviskahoro commented
Added you

2022-06-13 15:02 UTC, alokedesai requested changes
Apologies for the delay in reviewing here--I had reviewed this PR months ago but forgot to hit submit 😢 

High level--I think the most useful workflows are ones that involve running a hard-to-remember command with a lot of arguments or flags. 

Workflows that are one-to-one copied from an existing CLI that just add single flags or arguments are generally much less useful since they are easier to remember.

Would you mind combing through some of the these workflows and removing the ones that are 1:1 ports of ports of the documentation of the vercel CLI? Thanks so much!

2022-06-29 14:59 UTC, umarhadi commented on specs/git/commit_message_with_sign.yaml
> +description: "Using GPG or S/MIME, you can sign tags and commits locally. These tags or commits are marked as verified on GitHub Enterprise Server so other people can be confident that the changes co
done :)

2022-06-29 15:02 UTC, umarhadi commented
it's still relevant, thanks for the review. have a good day!

2023-01-13 23:27 UTC, alokedesai commented
@umarhadi Ping on the high level feedback here around some workflows that just seem to be regurgitations of a `man` page. There still seem to a few of these workflows (such as `specs/vercel/deploy_vercel_projects_from_specific_project_path.yaml` and `specs/vercel/perform_a_binary_search_upon_a_set_of_deployments_in_a_vercel_project.yaml`). LMK if you are still actively working on these--if not we should close out. Thanks!

2023-01-14 08:01 UTC, closed without merging